---
- hosts: tec
  tasks:
    - name: 'Instala o apache'
      apt:
        name: apache2
        state: latest     
      become: yes
    
    - name: 'Criar o diretório do site'
      ansible.builtin.file:
        path: /var/www/site
        state: directory
        mode: '755'
      become: yes

    - name: 'Cria arquivo html'
      ansible.builtin.file:
        path: /var/www/site/index.html
        state: touch
        mode: '755'
        notify:
          - restart apache2
      become: yes

  handlers:
    - name: 'restart apache2'
      service: name=apache2 state=restarted
